import { getEmbed } from './discord/converter.js';
import { parseTarget, sendToDiscord } from './discord/webhook.js';
import { WebhookError } from './errors.js';
import { parseRequest, verifySignature } from './github.js';
import { assertNotNoise } from './ignored.js';

// Lowercase only, which is what GitHub sends
const SIGNATURE = /^sha256=[0-9a-f]{64}$/;

/**
 * `Env` is generated by `wrangler types` from the `secrets.required` list in wrangler.jsonc:
 *
 * - `SECRET` - Secret token shared by every GitHub webhook that is pointed at this worker.
 */
export default {
	async fetch(request: Request, env: Env): Promise<Response> {
		if (request.method !== 'POST') {
			return text(405, 'Invalid request method.');
		}

		// Without a secret anyone could use the worker to post to Discord
		if (!env.SECRET) {
			console.error('SECRET is not set.');

			return text(500, 'Worker is not configured.');
		}

		try {
			return await handle(request, env.SECRET);
		} catch (error) {
			if (error instanceof WebhookError) {
				return text(error.status, error.message);
			}

			console.error('Failed to process webhook:', error);

			return text(500, 'Failed to process this event.');
		}
	},
} satisfies ExportedHandler<Env>;

async function handle(request: Request, secret: string): Promise<Response> {
	const signature = request.headers.get('X-Hub-Signature-256');

	// Nothing unsigned is worth reading the body for
	if (!signature || !SIGNATURE.test(signature)) {
		return unauthorized();
	}

	const body = await request.text();

	if (!(await verifySignature(secret, body, signature))) {
		return unauthorized();
	}

	// The Discord webhook is part of the url, which is only looked at once the request is known to be ours
	const target = parseTarget(new URL(request.url));
	const { eventType, repositoryName, displayName, avatarUrl, payload } = parseRequest(request, body);

	assertNotNoise(eventType, payload);

	// Several repositories usually share a webhook, the name and the avatar of the owner tell their messages apart.
	// The sender is already shown as the author of the embed.
	const message = {
		username: webhookUsername(displayName),
		avatar_url: avatarUrl,
		allowed_mentions: { parse: [] },
		...getEmbed(eventType, payload),
	};

	// Awaited rather than deferred so that GitHub's delivery log shows the real outcome
	const result = await sendToDiscord(target, message);
	const lines = [
		`Received ${eventType} in repository ${repositoryName}`,
		result.status === null ? `Discord request failed: ${result.error}` : `Discord HTTP ${result.status}`,
	];

	return text(result.ok ? 202 : 502, lines.join('\n'));
}

/** Discord rejects messages whose username is empty, too long or contains one of its reserved words. */
function webhookUsername(name: string): string | undefined {
	return name === '' || name.length > 80 || /discord|clyde|^(everyone|here)$/i.test(name) ? undefined : name;
}

/** Deliberately the same response whether the signature is missing or wrong. */
function unauthorized(): Response {
	return text(401, 'Secret validation failed.');
}

function text(status: number, message: string): Response {
	return new Response(`${message}\n`, {
		status,
		headers: { 'Content-Type': 'text/plain; charset=utf-8' },
	});
}
