import { getEmbed } from './discord/converter.js';
import { WebhookError } from './errors.js';
import { parseRequest, verifySignature } from './github.js';
import { matchPatterns, parseRouteConfig, sendAll, type RouteConfig } from './routing.js';

// Lowercase only, which is what GitHub sends
const SIGNATURE = /^sha256=[0-9a-f]{64}$/;

/**
 * `Env` is generated by `wrangler types` from the `secrets.required` list in wrangler.jsonc:
 *
 * - `REPOSITORIES` - JSON object mapping repository patterns to their secret and Discord webhook urls.
 */
export default {
	async fetch(request: Request, env: Env): Promise<Response> {
		if (request.method !== 'POST') {
			return text(405, 'Invalid request method.');
		}

		let config: RouteConfig;

		try {
			config = parseRouteConfig(env.REPOSITORIES);
		} catch (error) {
			console.error('Failed to parse REPOSITORIES:', error);

			return text(500, 'Worker is not configured.');
		}

		try {
			return await handle(request, config);
		} catch (error) {
			if (error instanceof WebhookError) {
				return text(error.status, error.message);
			}

			console.error('Failed to process webhook:', error);

			return text(500, 'Failed to process this event.');
		}
	},
} satisfies ExportedHandler<Env>;

async function handle(request: Request, config: RouteConfig): Promise<Response> {
	const signature = request.headers.get('X-Hub-Signature-256');

	// Nothing unsigned is worth reading the body for
	if (!signature || !SIGNATURE.test(signature)) {
		return unauthorized();
	}

	const body = await request.text();

	// Every repository has its own secret, so the payload has to be parsed to find out which one
	// to verify against. Until a signature is verified it is only used to look up that secret.
	const { eventType, repositoryName, displayName, avatarUrl, payload } = parseRequest(request, body);
	const checked = new Map<string, boolean>();
	const verified: string[] = [];

	for (const pattern of matchPatterns(config, repositoryName)) {
		const { secret } = config[pattern];

		// Patterns often share a secret, which only has to be checked once
		if (!checked.has(secret)) {
			checked.set(secret, await verifySignature(secret, body, signature));
		}

		if (checked.get(secret)) {
			verified.push(pattern);
		}
	}

	if (verified.length === 0) {
		console.warn(`Rejected ${eventType} for ${repositoryName}: no matching pattern with a valid secret.`);

		return unauthorized();
	}

	// Several repositories usually share a webhook, the name and the avatar of the owner tell their messages apart.
	// The sender is already shown as the author of the embed.
	const message = {
		username: webhookUsername(displayName),
		avatar_url: avatarUrl,
		allowed_mentions: { parse: [] },
		...getEmbed(eventType, payload),
	};
	const targets = [...new Set(verified.flatMap((pattern) => config[pattern].webhooks))];
	const lines = [
		`Received ${eventType} in repository ${repositoryName}`,
		...verified.map((pattern) => `Matched "${repositoryName}" as "${pattern}"`),
	];

	if (targets.length === 0) {
		lines.push('No Discord webhooks are configured, nothing was sent.');

		return text(202, lines.join('\n'));
	}

	// Awaited rather than deferred so that GitHub's delivery log shows the real outcome
	const results = await sendAll(targets, message);

	for (const result of results) {
		lines.push(result.status === null ? `Discord request failed: ${result.error}` : `Discord HTTP ${result.status}`);
	}

	return text(results.some((result) => result.ok) ? 202 : 502, lines.join('\n'));
}

/** Discord rejects messages whose username is empty, too long or contains one of its reserved words. */
function webhookUsername(name: string): string | undefined {
	return name === '' || name.length > 80 || /discord|clyde|^(everyone|here)$/i.test(name) ? undefined : name;
}

/** Deliberately the same response whether the signature is missing, wrong, or the repository is not configured. */
function unauthorized(): Response {
	return text(401, 'Secret validation failed.');
}

function text(status: number, message: string): Response {
	return new Response(`${message}\n`, {
		status,
		headers: { 'Content-Type': 'text/plain; charset=utf-8' },
	});
}
